
#General settings
[general]
	#Disables Optifine warn screen
	no_optifine_warn_screen = false
	#Disables Amendments suggestion screen
	no_amendments_screen = true
	#Disable incompatible mods warning screen
	no_incompatible_mods_screen = false